name: the_king_of_delivery
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  mask_text_input_formatter: ^2.8.0
  badges: ^2.0.3
  geolocator: ^10.1.0
  provider: ^6.1.1
  google_maps_flutter: ^2.5.3
  flutter_config: ^2.0.2
  get: ^4.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/food1.png
    - assets/food.png

